# Generated by Django 2.2.9 on 2023-03-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otime', models.DateField(verbose_name='预约时间')),
                ('omemnum', models.IntegerField(default=1, verbose_name='预约人数')),
                ('sname', models.CharField(default='', max_length=100, verbose_name='景区名称')),
                ('oname', models.CharField(default='', max_length=100, verbose_name='联系人')),
                ('ophone', models.CharField(default='', max_length=11, verbose_name='联系电话')),
                ('oremark', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('totalprice', models.IntegerField(default=0, verbose_name='总价格')),
            ],
            options={
                'verbose_name': '预约详情',
                'verbose_name_plural': '预约详情',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=100, verbose_name='城市')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(default='', max_length=100, verbose_name='景点名称')),
                ('spicture', models.ImageField(upload_to='simage/', verbose_name='景区图片')),
                ('sdesc', models.CharField(default='', max_length=500, verbose_name='景区介绍')),
                ('sprice', models.IntegerField(default=0, verbose_name='景区价格')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Province', verbose_name='城市')),
            ],
            options={
                'verbose_name': '景区详情',
                'verbose_name_plural': '景区详情',
            },
        ),
    ]
